version: '3'

services:
  dnsauth:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: us-central1-docker.pkg.dev/devops-capstone-project-395319/dns-authoritative/dns-authoritative:latest
    container_name: dns-authoritative
    hostname: dns-authoritative
    environment:
      - BIND9_USER=bind
      - TZ=EAT
    expose:
      - "53"
      - "5353"
    ports:
      - "5301:53/tcp"
      - "5301:53/udp"
      - "953:953/tcp"
    networks:
      - main_v4_v6
    volumes:
      - ./config:/etc/bind:rw
    restart: unless-stopped
networks:
  main_v4_v6:
    external: true